version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/deploy/nest/zip/

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 1200
      runas: ubuntu